### ISSUE TITLE
Make MOODLE_USER_ID available when executing vpl_evaluate.sh

### ISSUE THREAD

**Issue by aivarannamaa** [jcrodriguez-dis/vpl-xmlrpc-jail#10]
The compilation phase can be useful for making user-dependent pre-processing for the submission, but currently MOODLE_USER_ID is not available at this phase.

**Comment by jcrodriguez-dis** [comment]
Hello Aivar,
this feature is ready to be release in the 3.1.5 version see it at
https://github.com/jcrodriguez-dis/moodle-mod_vpl/commits/v3.1.5/vpl_submission_CE.class.php
https://github.com/jcrodriguez-dis/moodle-mod_vpl/commit/9256a4a998a19b34fcf2f6c379566ff3f92432a2#diff-ee976a36829515ade3fef48050d87ef6

Best regards.

**Comment by aivarannamaa** [comment]
Sorry, my mistake. I had a custom vpl_evaluate script and I forgot running vpl_environment.sh
