### ISSUE TITLE
Poodle SSL problem

### ISSUE THREAD

**Issue by asabolansky** [jcrodriguez-dis/vpl-xmlrpc-jail#13]
When we analize the Poodle Vulnerabilty in the VPL Server host, we detect that the SSL server in the jail has Poodle bug.

**Comment by jcrodriguez-dis** [comment]
This issue is already resolved.
Use the 2.2.1 version
see https://github.com/jcrodriguez-dis/vpl-xmlrpc-jail/issues/8
