### ISSUE TITLE
Install failed (Debian 9)

### ISSUE THREAD

**Issue by fwsl** [jcrodriguez-dis/vpl-xmlrpc-jail#14]
Hi,

I've tried to install v2.2.1 on clean Debian 9 but got these errors. Could you try to reproduce the problem?

Preparing the installation
Installing make: make [OK]
Installing C++ compiler: g++ [OK]
Installing SSL library: openssl [OK]
Installing SSL library: libssl-dev [OK]
Installing Firewall: iptables [OK]
Installing X system: xorg [OK]
Installing VNC server: tightvncserver [OK]
Installing Fonts: xfonts-75dpi [OK]
Installing Fonts: xfonts-100dpi [OK]
Installing Window manager: openbox [OK]
Installing Configuration DB system: gconf2 [OK]
Installing Web browser: [Package not found. Checked  firefox
Checking installed software
Compiling vpl-jail-server
vpl-jail-server.o: In function `SSLSocket::~SSLSocket()':
/opt/vpl-jail-system-2.2.1/src/socket.h:223: undefined reference to `SSL_free'
vpl-jail-server.o: In function `SSLSocket::~SSLSocket()':
/opt/vpl-jail-system-2.2.1/src/socket.h:223: undefined reference to `SSL_free'
vpl-jail-server.o: In function `SSLSocket::netRead(void*, unsigned long)':
/opt/vpl-jail-system-2.2.1/src/socket.h:205: undefined reference to `SSL_read'
vpl-jail-server.o: In function `SSLRetry::end(long)':
/opt/vpl-jail-system-2.2.1/src/socket.h:136: undefined reference to `SSL_get_error'
vpl-jail-server.o: In function `SSLSocket::netWrite(void const*, unsigned long)':
/opt/vpl-jail-system-2.2.1/src/socket.h:197: undefined reference to `SSL_write'
vpl-jail-server.o: In function `SSLRetry::end(long)':
/opt/vpl-jail-system-2.2.1/src/socket.h:136: undefined reference to `SSL_get_error'
vpl-jail-server.o: In function `SSLBase::getSSLBase()':
/opt/vpl-jail-system-2.2.1/src/socket.h:28: undefined reference to `OPENSSL_init_ssl'
/opt/vpl-jail-system-2.2.1/src/socket.h:30: undefined reference to `OPENSSL_init_ssl'
/opt/vpl-jail-system-2.2.1/src/socket.h:31: undefined reference to `TLS_server_method'
/opt/vpl-jail-system-2.2.1/src/socket.h:36: undefined reference to `SSL_CTX_new'
/opt/vpl-jail-system-2.2.1/src/socket.h:40: undefined reference to `SSL_CTX_use_certificate_chain_file'
/opt/vpl-jail-system-2.2.1/src/socket.h:44: undefined reference to `SSL_CTX_use_PrivateKey_file'
/opt/vpl-jail-system-2.2.1/src/socket.h:48: undefined reference to `SSL_CTX_check_private_key'
/opt/vpl-jail-system-2.2.1/src/socket.h:52: undefined reference to `SSL_CTX_set_options'
/opt/vpl-jail-system-2.2.1/src/socket.h:54: undefined reference to `SSL_CTX_ctrl'
vpl-jail-server.o: In function `SSLSocket::SSLSocket(int)':
/opt/vpl-jail-system-2.2.1/src/socket.h:212: undefined reference to `SSL_new'
/opt/vpl-jail-system-2.2.1/src/socket.h:214: undefined reference to `SSL_set_fd'
/opt/vpl-jail-system-2.2.1/src/socket.h:218: undefined reference to `SSL_accept'
vpl-jail-server.o: In function `SSLRetry::end(long)':
/opt/vpl-jail-system-2.2.1/src/socket.h:136: undefined reference to `SSL_get_error'
vpl-jail-server.o: In function `SSLBase::getSSLBase()':
/opt/vpl-jail-system-2.2.1/src/socket.h:28: undefined reference to `OPENSSL_init_ssl'
/opt/vpl-jail-system-2.2.1/src/socket.h:30: undefined reference to `OPENSSL_init_ssl'
/opt/vpl-jail-system-2.2.1/src/socket.h:31: undefined reference to `TLS_server_method'
/opt/vpl-jail-system-2.2.1/src/socket.h:36: undefined reference to `SSL_CTX_new'
/opt/vpl-jail-system-2.2.1/src/socket.h:40: undefined reference to `SSL_CTX_use_certificate_chain_file'
/opt/vpl-jail-system-2.2.1/src/socket.h:44: undefined reference to `SSL_CTX_use_PrivateKey_file'
/opt/vpl-jail-system-2.2.1/src/socket.h:48: undefined reference to `SSL_CTX_check_private_key'
/opt/vpl-jail-system-2.2.1/src/socket.h:52: undefined reference to `SSL_CTX_set_options'
/opt/vpl-jail-system-2.2.1/src/socket.h:54: undefined reference to `SSL_CTX_ctrl'
/opt/vpl-jail-system-2.2.1/src/socket.h:28: undefined reference to `OPENSSL_init_ssl'
/opt/vpl-jail-system-2.2.1/src/socket.h:30: undefined reference to `OPENSSL_init_ssl'
/opt/vpl-jail-system-2.2.1/src/socket.h:31: undefined reference to `TLS_server_method'
/opt/vpl-jail-system-2.2.1/src/socket.h:36: undefined reference to `SSL_CTX_new'
/opt/vpl-jail-system-2.2.1/src/socket.h:40: undefined reference to `SSL_CTX_use_certificate_chain_file'
/opt/vpl-jail-system-2.2.1/src/socket.h:44: undefined reference to `SSL_CTX_use_PrivateKey_file'
/opt/vpl-jail-system-2.2.1/src/socket.h:48: undefined reference to `SSL_CTX_check_private_key'
/opt/vpl-jail-system-2.2.1/src/socket.h:52: undefined reference to `SSL_CTX_set_options'
/opt/vpl-jail-system-2.2.1/src/socket.h:54: undefined reference to `SSL_CTX_ctrl'
processMonitor.o: In function `SSLBase::getSSLBase()':
/opt/vpl-jail-system-2.2.1/src/socket.h:28: undefined reference to `OPENSSL_init_ssl'
/opt/vpl-jail-system-2.2.1/src/socket.h:30: undefined reference to `OPENSSL_init_ssl'
/opt/vpl-jail-system-2.2.1/src/socket.h:31: undefined reference to `TLS_server_method'
/opt/vpl-jail-system-2.2.1/src/socket.h:36: undefined reference to `SSL_CTX_new'
/opt/vpl-jail-system-2.2.1/src/socket.h:40: undefined reference to `SSL_CTX_use_certificate_chain_file'
/opt/vpl-jail-system-2.2.1/src/socket.h:44: undefined reference to `SSL_CTX_use_PrivateKey_file'
/opt/vpl-jail-system-2.2.1/src/socket.h:48: undefined reference to `SSL_CTX_check_private_key'
/opt/vpl-jail-system-2.2.1/src/socket.h:52: undefined reference to `SSL_CTX_set_options'
/opt/vpl-jail-system-2.2.1/src/socket.h:54: undefined reference to `SSL_CTX_ctrl'
collect2: error: ld returned 1 exit status
make[2]: *** [vpl-jail-server] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Updating installation => /etc/vpl
cp: cannot stat 'src/vpl-jail-server': No such file or directory

**Comment by jcrodriguez-dis** [comment]
Hello fwsl,
at first glance it seems that the openssl library is missing at link stage.
It may be that configuration.ac requieres some fixes.
Notice that vpl-jail-server is tested on Ubuntu.
I need some time to reproduce and resolve this problem.

Best regards,
Juan Carlos.

**Comment by Bevito** [comment]
Hi, 

Same problem here with vpl-jail-system-2.2.2 and (Debian 9.1)
I know there is a difference in package name for libssl : 
- Debian Jessie (8.x)  : libssl-dev
- Debian Stretch (9.x) : libssl1.0-dev

Is there a way to help you solve this issue ?

Best regards.
Bevito

INSTALLING VPL-JAIL-SYSTEM
==========================
Detected Ubuntu or similar distribution (using update-rc.d)
Updating distribution software DB
Installation log file => installation.log
Preparing the installation
Installing make: make [OK]
Installing C++ compiler: g++ [OK]
Installing SSL library: openssl [OK]
Installing SSL library: libssl-dev [OK]
Installing Firewall: iptables [OK]
Installing X system: xorg [OK]
Installing VNC server: tightvncserver [OK]
Installing Fonts: xfonts-75dpi [OK]
Installing Fonts: xfonts-100dpi [OK]
Installing Window manager: openbox [OK]
Installing Configuration DB system: gconf2 [OK]
Installing Web browser: [Package not found. Checked  firefox
Checking installed software
Compiling vpl-jail-server
vpl-jail-server.o : Dans la fonction « SSLSocket::~SSLSocket() » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:223 : référence indéfinie vers « SSL_free »
vpl-jail-server.o : Dans la fonction « SSLSocket::~SSLSocket() » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:223 : référence indéfinie vers « SSL_free »
vpl-jail-server.o : Dans la fonction « SSLSocket::netRead(void*, unsigned long) » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:205 : référence indéfinie vers « SSL_read »
vpl-jail-server.o : Dans la fonction « SSLRetry::end(long) » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:136 : référence indéfinie vers « SSL_get_error »
vpl-jail-server.o : Dans la fonction « SSLSocket::netWrite(void const*, unsigned long) » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:197 : référence indéfinie vers « SSL_write »
vpl-jail-server.o : Dans la fonction « SSLRetry::end(long) » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:136 : référence indéfinie vers « SSL_get_error »
vpl-jail-server.o : Dans la fonction « SSLBase::getSSLBase() » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:28 : référence indéfinie vers « OPENSSL_init_ssl »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:30 : référence indéfinie vers « OPENSSL_init_ssl »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:31 : référence indéfinie vers « TLS_server_method »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:36 : référence indéfinie vers « SSL_CTX_new »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:40 : référence indéfinie vers « SSL_CTX_use_certificate_chain_file »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:44 : référence indéfinie vers « SSL_CTX_use_PrivateKey_file »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:48 : référence indéfinie vers « SSL_CTX_check_private_key »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:52 : référence indéfinie vers « SSL_CTX_set_options »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:54 : référence indéfinie vers « SSL_CTX_ctrl »
vpl-jail-server.o : Dans la fonction « SSLSocket::SSLSocket(int) » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:212 : référence indéfinie vers « SSL_new »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:214 : référence indéfinie vers « SSL_set_fd »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:218 : référence indéfinie vers « SSL_accept »
vpl-jail-server.o : Dans la fonction « SSLRetry::end(long) » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:136 : référence indéfinie vers « SSL_get_error »
vpl-jail-server.o : Dans la fonction « SSLBase::getSSLBase() » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:28 : référence indéfinie vers « OPENSSL_init_ssl »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:30 : référence indéfinie vers « OPENSSL_init_ssl »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:31 : référence indéfinie vers « TLS_server_method »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:36 : référence indéfinie vers « SSL_CTX_new »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:40 : référence indéfinie vers « SSL_CTX_use_certificate_chain_file »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:44 : référence indéfinie vers « SSL_CTX_use_PrivateKey_file »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:48 : référence indéfinie vers « SSL_CTX_check_private_key »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:52 : référence indéfinie vers « SSL_CTX_set_options »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:54 : référence indéfinie vers « SSL_CTX_ctrl »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:28 : référence indéfinie vers « OPENSSL_init_ssl »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:30 : référence indéfinie vers « OPENSSL_init_ssl »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:31 : référence indéfinie vers « TLS_server_method »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:36 : référence indéfinie vers « SSL_CTX_new »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:40 : référence indéfinie vers « SSL_CTX_use_certificate_chain_file »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:44 : référence indéfinie vers « SSL_CTX_use_PrivateKey_file »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:48 : référence indéfinie vers « SSL_CTX_check_private_key »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:52 : référence indéfinie vers « SSL_CTX_set_options »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:54 : référence indéfinie vers « SSL_CTX_ctrl »
processMonitor.o : Dans la fonction « SSLBase::getSSLBase() » :
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:28 : référence indéfinie vers « OPENSSL_init_ssl »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:30 : référence indéfinie vers « OPENSSL_init_ssl »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:31 : référence indéfinie vers « TLS_server_method »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:36 : référence indéfinie vers « SSL_CTX_new »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:40 : référence indéfinie vers « SSL_CTX_use_certificate_chain_file »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:44 : référence indéfinie vers « SSL_CTX_use_PrivateKey_file »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:48 : référence indéfinie vers « SSL_CTX_check_private_key »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:52 : référence indéfinie vers « SSL_CTX_set_options »
/usr/local/src/vpl-jail-system-2.2.2/src/socket.h:54 : référence indéfinie vers « SSL_CTX_ctrl »
collect2: error: ld returned 1 exit status
make[2]: *** [vpl-jail-server] Erreur 1
make[1]: *** [all-recursive] Erreur 1
make: *** [all] Erreur 2
Updating installation => /etc/vpl
cp: impossible d'évaluer 'src/vpl-jail-server': Aucun fichier ou dossier de ce type
cp : voulez-vous écraser '/etc/vpl/vpl-jail-system.conf' ? ^C

**Comment by Bevito** [comment]
Hi, 

This bug should be closed, as vpl-jail-server 2.2.2 (stable) compile with Debian 9.4

Thanks a lot for your work !
