### ISSUE TITLE
Two errors: 1 common cause?

### ISSUE THREAD

**Issue by gnewport** [jcrodriguez-dis/vpl-xmlrpc-jail#17]
We have our jail server running, and the system is evaluating submissions. Yet the input/output expectations are incorrectly aligned.

We have code that accepts an INPUT (a whole value, let's say, such as 129).
The code then analyses this input and generates the OUTPUT 10000001.

I have set up the vpl_evaluate.cases to:
**case=Denary to Binary
input=109
output=01101101**

I have given the requested file the following code:
**position = 128
binary = ""
denary = input("Please enter your denary whole number, between 0 and 255: ")
 
### YOUR CODE GOES HERE ###

print(binary)**

When a student tries to evaluate the code we get an out of memory error (64MiB), and then, after several attempts, we get a completed evaluation.

However, the evaluation fails.

The system reports that the input was:
129

And that the output was:
Please enter your denary value: 10000001

With the expected output to be 10000001

It appears that VPL is issuing the input prior to being requested, then issuing the output as input.

What am I getting wrong here?

**Comment by jcrodriguez-dis** [comment]
Hello gnewport,
the two problems you describe are related to the setting of the VPL activity.

To resolve the first problem, please, increase the "Maximum memory used" at "Advanced settings > Maximum execution resources limits" of your activity.

The second problem is related to how the system works. The system sends the input to the student program and get its output. In this case the input is not show in the output (the program don't echo the input). This behaviour is common. There are different output check types (text, number, exact text, regular expressions). You have set a number or numbers check output (integer decimal), the system will test if the output contents the number(s). In this case, for the data shown, the test must be passed. 

Notice that if you test a large number, the binary result (interpreted as decimal) may be out of range. I recommend you to use a regular expression to check this type of program output.

Sorry for the answer delay.

Best regards,
Juan Carlos.
