### ISSUE TITLE
syntax error near unexpected token

### ISSUE THREAD

**Issue by Supper1990** [jcrodriguez-dis/vpl-xmlrpc-jail#18]
evaluate do not work. execute works fine
/home/p18702/vpl_evaluate.sh: line 26: syntax error near unexpected token `>' /home/p18702/vpl_evaluate.sh: line 26: ` ./vpl_run.sh &>>vpl_compilation_error.txt' 

can you help me?
 FPC, Altlinux

**Comment by jcrodriguez-dis** [comment]
Hello Supper1990,
this command is compatible with "bash" but not with "sh".
are you using a shell different than bash"?

Best regards.
