### ISSUE TITLE
Package requeriments in ubuntu

### ISSUE THREAD

**Issue by alphonse92** [jcrodriguez-dis/vpl-xmlrpc-jail#21]
Could you specify the package requeriments for install the jail in a ubuntu server. For tries to dockerize the image.

**Comment by jcrodriguez-dis** [comment]
tarting from a Ubuntu-server:
make
g++
openssl
libssl-dev
iptables
xorg
tightvncserver
xfonts-75dpi
xfonts-100dpi
openbox
gconf2
firefox
If you you start from a more "clean" Ubuntu you may need other packages.
