### ISSUE TITLE
Enabling vpl jail service blocks ssh connections

### ISSUE THREAD

**Issue by dufferzafar** [jcrodriguez-dis/vpl-xmlrpc-jail#24]
I've install VPL Jail v2.2.2 on Ubuntu 16.04 and enabling the service somehow prevents new incoming ssh connections.

sshd is still running on the machine, but new SSH connections don't happen.

As soon as I stop the vpl-jail service, new ssh connections start happening.

**Comment by jcrodriguez-dis** [comment]
Hi dufferzaar.
the default VPL executaion demon configuration close your machine for external connections others tnan the remote execution service. You must modify /etc/vpl/vpl-jail-system.conf file setting FIREWALL=0 to allow external connections.

Best regards,
Juan Carlos.
