### ISSUE TITLE
VPL Jail service startup removes home directories

### ISSUE THREAD

**Issue by fcafagna** [jcrodriguez-dis/vpl-xmlrpc-jail#25]
Hi, 
I have upgraded my server to Debian 9, and my Moodle installation to 3.6.2 as well.
VPL plugin has been automatically updated to version 3.3.3. 
The jail version installed on the previous Debian 8, was the version 2.2.2. 
I am using VPL for C++ language. 
At a first glance everything was working well, but when I tried to debug a code, the DDD was not starting and I got just a blue screen, instead of the virtual desktop, as usual.
So I tried to reinstall the jail, but I got several compilation issue related to the SSL libraries. 
For this I followed the link, in the download page, to the "Previous versions" repository, and noticed a more recent build of the 2.2.2 version along with a 2.2.3 and a 2.3.0. 
I tried both 2.2.2 and 2.2.3; the latest compiled fine, but I still got the "blue screen" on the virtual desktop, instead of the DDD windows. 
A this point I decided to install the 2.3.0 and everything was fine, compilation, as well as the VPL debugging version. 
Unfortunately all /home directories were gone!!!
I noticed that the service startup simply deletes the home directories! 

I was of course wrong in installing a version that is not yet officially released, but there is something nasty in this release, that is causing such a disaster. 
Can you please help me in fixing this? 
Thanks for your attention, 
Francesco

**Comment by jcrodriguez-dis** [comment]
Hello Francesco,
Apologize for the mess of deleting your "/home".
After your problem using an unstable version, I have added the suffix "unstable" to this type of alpha/beta versions.

You can find the "unstable" 2.3.0.1 version that resolves the "rm /home" problem at the  "Previous versions" repository ;). Please, notice the "UNSTABLE" name.

Best regards,
Juan Carlos.

**Comment by fcafagna** [comment]
Ciao Juan Carlos, 

thanks a lot. 
It is working now. 
I hope this version will be promoted to "stable" soon. I need it for the Debian 9 installation and, unfortunately, the 2.2 doesn't work with the DDD. 

Best regards, 
Francesco
