### ISSUE TITLE
Daemon doesn't start after the installation of execution jail server

### ISSUE THREAD

**Issue by iMinion** [jcrodriguez-dis/vpl-xmlrpc-jail#3]
Hello @jcrodriguez-dis ,

I'm also experiencing the similar problem! I've even ran the command "sudo service vpl-jail-system start -d 8".
Right now I'm using 2.1.1 Jail Server on a Ubuntu based Virtual Machine.

Here's what I get in the logs

> Jun 3 11:37:28 jailserver vpl-jail-system[8253]: Set log mask up to 8
> Jun 3 11:37:28 jailserver vpl-jail-system[8253]: correctFile 1 'jail' 0:0
> Jun 3 11:37:28 jailserver vpl-jail-system[8253]: correctFile 1 'var' 0:0
> Jun 3 11:37:28 jailserver vpl-jail-system[8253]: correctFile 1 'vpl-jail-system' 0:0
> Jun 3 11:37:28 jailserver vpl-jail-system[8253]: SSL_CTX_use_certificate_chain_file() fail: error:02001002:system library:fopen:No such file or directory

The ports aren't being used by any other processes or services

Thanks,
Sri Ram Manoj K

**Comment by jcrodriguez-dis** [comment]
Hi Sir Ram Manoj K,
the error message says that the daemon don't found the SSL certificate file "/etc/vpl/cert.pem".

Please check that you have a valid certificate file at /etc/vpl/cert.pem (and a key file at /etc/vpl/key.pem)

If you want that the jail system creates a new autosigned SSL certificate for you, then rerun the installation script with "sudo ./install-vpl-sh" and let the script generate the SSL needed files.

Please, let me know if this resolve your problem.

Best regards.
