### ISSUE TITLE
Adding packages by demand

### ISSUE THREAD

**Issue by alphonse92** [jcrodriguez-dis/vpl-xmlrpc-jail#30]
Could be very very cool install development packages by demand. Not all software development packages are using really. Most universities focus at most 2 or 3 programming languages. Sometimes i need push a lot of effort to install or package the jail into container for example. 

My proposal is read a Json (or other format) with the required dependencies, and install them by demand for the vpl installer.

Just a proposal.

**Comment by jcrodriguez-dis** [comment]
Hi Alejandro,
Yes, it could be a good idea to select by menu or by config file the programming languages and then install the needed packages.  I add this request to the TODO list.
In any case, you must notice that the installation of packages in the VPL installer is help and has no direct relationship with the configuration of VPL. You can install or update manually or programmatically the packages you need before (or after) the  VPL installation. Then you must restart the service to use the new (or updated) software.

Best regard,
Juan Carlos
