### ISSUE TITLE
Add the hability to choose how to run the service

### ISSUE THREAD

**Issue by alphonse92** [jcrodriguez-dis/vpl-xmlrpc-jail#31]
We are need a way to start the service by our own. In some docker enviroments service managers like systemctl does not working. So we need a way to start the service by our own.

I resolved that with:

```sh
./vpl-jail-system stop
./vpl-jail-system start
```

the service run successfully

**Comment by alphonse92** [comment]
Update, we could use http://supervisord.org/introduction.html

**Comment by jcrodriguez-dis** [comment]
I think that it may be better to use the absolute path
/etc/vpl/vpl-jail-system [start|stop|restart]
About the use of "supervisord", any propose?

**Comment by alphonse92** [comment]
Not yet, im using that to "monitoring" the process.  Im using that in my project: https://github.com/alphonse92/vplplusplus_jail

**Comment by jcrodriguez-dis** [comment]
Nice project

Best regards,
Juan Carlos.

**Comment by alphonse92** [comment]
That project belongs to other big project https://github.com/alphonse92/vplplusplus_composer
