### ISSUE TITLE
Is the outcoming request denied? 

### ISSUE THREAD

**Issue by alphonse92** [jcrodriguez-dis/vpl-xmlrpc-jail#32]
Im playing with the jail. As a teacher i trying to run some tests. For example:

<img width="979" alt="Screen Shot 2019-11-11 at 9 21 07 PM" src="https://user-images.githubusercontent.com/18203585/68636336-3574b500-04c9-11ea-9671-537014ea190f.png">

as you can see, those host cant be resolved.

But if inside the jail host i can reach those urls:

<img width="475" alt="Screen Shot 2019-11-11 at 9 30 03 PM" src="https://user-images.githubusercontent.com/18203585/68636750-8b962800-04ca-11ea-96b4-b3a6d92c2a68.png">

Why ?  How can i resolve specific domains?

**Comment by alphonse92** [comment]
How can i resolve specific domains?

**Comment by alphonse92** [comment]
btw, i solved.

Just run:
```
echo '172.217.172.4 www.google.com' >>  /jail/etc/host
```

Obviously, I changed the ip and the hostname as i was needing. I will close this issue, but someone could need this information.

**Comment by jcrodriguez-dis** [comment]
Notice the FIREWALL jail parameter
Use value 1 or 0

#FIREWALL=0|1|2|3|4
#0: No firewall
#1: VPL service+DNS+internet access
#2: VPL service+DNS+Limit Internet to port 80 (super user unlimited)
#3: VPL service+No external access (super user unlimited)
#4: VPL service+No external access
#Note: In level 4 stop vpl-jail-system service to update/upgrade the system
#Note: Don not use in CentOS
#default level 0
FIREWALL=0

**Comment by alphonse92** [comment]
Yeah the firewall is disable right now. (By default). The is a docker issue mostly.
