### ISSUE TITLE
Jail Server fails to start deamon after installation

### ISSUE THREAD

**Issue by asbl** [jcrodriguez-dis/vpl-xmlrpc-jail#38]
I tried to install jail server on  a clean debian 10 distro. After the installation the script cannot stat the daemon. I have no further information.

When I try to install (or reinstall) the jail server, I see the following errors before installing the ssl-certificate. Maybe thats where the error occurs?

Compiling vpl-jail-server
/usr/bin/ld: vpl-jail-server.o: in function `SSLSocket::~SSLSocket()':
/home/a_user/vpl-jail-system-2.0.3/src/socket.h:180: undefined reference to `SSL_free'
/usr/bin/ld: vpl-jail-server.o: in function `SSLSocket::~SSLSocket()':
/home/a_user/vpl-jail-system-2.0.3/src/socket.h:180: undefined reference to `SSL_free'
/usr/bin/ld: vpl-jail-server.o: in function `SSLBase::SSLBase()':
/home/a_user/vpl-jail-system-2.0.3/src/socket.h:29: undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:31: undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:32: undefined reference to `TLS_server_method'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:37: undefined reference to `SSL_CTX_new'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:41: undefined reference to `SSL_CTX_use_certificate_file'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:45: undefined reference to `SSL_CTX_use_PrivateKey_file'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:49: undefined reference to `SSL_CTX_check_private_key'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:53: undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: vpl-jail-server.o: in function `SSLSocket::netWrite(void const*, unsigned long)':
/home/a_user/vpl-jail-system-2.0.3/src/socket.h:156: undefined reference to `SSL_write'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:129: undefined reference to `SSL_get_error'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:126: undefined reference to `SSL_get_error'
/usr/bin/ld: vpl-jail-server.o: in function `SSLSocket::netRead(void*, unsigned long)':
/home/a_user/vpl-jail-system-2.0.3/src/socket.h:163: undefined reference to `SSL_read'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:129: undefined reference to `SSL_get_error'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:126: undefined reference to `SSL_get_error'
/usr/bin/ld: vpl-jail-server.o: in function `Daemon::launch(int, bool)':
/home/a_user/vpl-jail-system-2.0.3/src/socket.h:169: undefined reference to `SSL_new'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:171: undefined reference to `SSL_set_fd'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:175: undefined reference to `SSL_accept'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:129: undefined reference to `SSL_get_error'
/usr/bin/ld: /home/a_user/vpl-jail-system-2.0.3/src/socket.h:126: undefined reference to `SSL_get_error'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:371: vpl-jail-server] Error 1
make[1]: *** [Makefile:398: all-recursive] Error 1
make: *** [Makefile:317: all] Error 2
Updating installation => /etc/vpl
cp: cannot stat 'src/vpl-jail-server': No such file or directory
cp: overwrite '/etc/vpl/vpl-jail-system.conf'?

**Comment by jcrodriguez-dis** [comment]
Hi asbl.

Please, try using the last version released [vpl-jail-system-2.5.3.tar.gz](https://vpl.dis.ulpgc.es/releases/vpl-jail-system-2.5.3.tar.gz). It seems that you are trying to install a deprecated one. If you still want to install this old version you must run before (as root):
apt install openssl libssl-dev

Best regards,
Juan Carlos.

**Comment by asbl** [comment]
Hello Juan

Thanx! I must have spent an hour looking for the error, but I didn't notice the typo in the version... Thank you for pointing that out.
