### ISSUE TITLE
Readme-Link update

### ISSUE THREAD

**Issue by ivancho2** [jcrodriguez-dis/vpl-xmlrpc-jail#39]
please update the link in readme. currently redirects  to https://vp.dis.ulpgc.es [404]

Correct: https://vpl.dis.ulpgc.es  (with L )

**Comment by jcrodriguez-dis** [comment]
Resolved in https://github.com/jcrodriguez-dis/vpl-xmlrpc-jail/commit/321c6f5331d3102e1b8427a8b703cc2e5981d9ec. Thanks @ivancho2 #.

**Comment by jeroenhabets** [comment]
@ivancho2 can you close this issue, pls? TIA!
