### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by charliedaly** [jcrodriguez-dis/vpl-xmlrpc-jail#4]
I installed version 2.1 of the jail execution server onto a freshly installed Ubuntu 14.04.3 Virtual Machine and it seemed to do everything correctly until the end.

Unfortunately, I can't remember the name
Then the script complained that it couldn't stat /etc/vpl/vpl-jail-system

The file did exist in /etc/init.d/

I couldn't fix the problem.

**Comment by jcrodriguez-dis** [comment]
As soon as possible, I'll try to reproduce the problem to resolve it.

**Comment by jcrodriguez-dis** [comment]
Hello Charlie,
Sorry for the very late answer. I have tried to reproduce the problem with no luck. The jail server 2.1.1 (the last one when you reported the problem) seems to install and go well in a freshly installed Ubuntu 14.04.3.

You can upload the installation.log file to check for errors.

**Comment by charliedaly** [comment]
Hi Juan,
I am sorry I didn't keep the installation log, so I don't know what the 
problem was, but I am now using the current version without problems.

I have to thank you for a very nice system.

By the way, I do have a plan for setting up a repository of problems, 
though it may not come to fruition.

Also, I have some ideas for a wishlist. You may have too many ideas 
already to bother with them. But is there a place where wishlist items 
could be posted?
Thanks.

(And sorry for wasting your time with that last bug)

Charlie

**Comment by mohita-12** [comment]
I installed version 2.2.1 of the jail execution server onto Ubuntu 16.04 but I am not able to check the availability of my execution server using the URL
http://server:PORT/OK and https://server:SECURE_PORT/OK
where server is the name of your execution server.
The system is not returning a page with OK.
I am not able to fix this problem so please help.

**Comment by jcrodriguez-dis** [comment]
Hello mohita-12,
please, gives more details about your installation. Notice, that this installation seems to be ok in the case that you describe.

* are you using a firewall?
* are you using a web server?
* have you set non standard ports?
* have you set the "URLPATH" parm?

Best regards,
Juan Carlos.

**Comment by fwsl** [comment]
@mohita-12  check if you are testing http://server:PORT/OK or http://server:PORT/ok
OK should work
ok gives: Not found Url path not found '/ok'

@jcrodriguez-dis could this be changed to work in both cases?

**Comment by jcrodriguez-dis** [comment]
Yes.
I have Added this request to the TODO list.
This request is easy to resolve, but it is not a bug => low priority.

Best regards,
Juan Carlos.
