### ISSUE TITLE
Website down.

### ISSUE THREAD

**Issue by DaveDavenport** [jcrodriguez-dis/vpl-xmlrpc-jail#47]
FYI: The website http://vpl.dis.ulpgc.es/  is not working for me (and others).

**Comment by jcrodriguez-dis** [comment]
Apologies for the inconvenience, Dave. The building that hosts the servers is in electricity cut for maintenance. The power will be restored in a few hours.

J.C.

**Comment by DaveDavenport** [comment]
No problem, thanks for the great tool!
