### ISSUE TITLE
Future plans, in particular around XML-RPC?

### ISSUE THREAD

**Issue by jeroenhabets** [jcrodriguez-dis/vpl-xmlrpc-jail#49]
Hi,

While exploring the possibilities of a C# / .Net Core client for VPL I noticed:

- .Net XML-RPC packages have seen little tender love and care.
- PHP is unbundling XML-RPC (https://php.watch/versions/8.0/xmlrpc)
- VPL Jail seems rather dormant (though still seeing occasional maintenance)

which makes me wonder about your plans around VPL jail. And if it's still worth investing in VPL and an XML-RPC solution. E.g. if there is a redesign in the works, I'd love to hear about it.

Thank you in advance.

**Comment by jeroenhabets** [comment]
See also Moodle discussion "XMLRPC abandoned in php 8": https://moodle.org/mod/forum/discuss.php?d=426310

**Comment by jcrodriguez-dis** [comment]
Dear jeroenhabets.
We are conscious that XML-RPC will be removed from the PHP mainstream. Replace the XML-RPC protocol for JSON is required to keep VPL running with no problem in the next PHP versions.
Notice that the changes will be required in the VPL Jail and the VPL Moodle plugin. Replace XML-RPC on both software is now our main priority.

Best regards,
Juan Carlos.

**Comment by jeroenhabets** [comment]
Dear Juan Carlos,

Thank you very much for that information!

FYI: We have our own VPL client in C#/.Net and C++ that we need to update/upgrade in 2022 ideally to pure C#/.Net so I'll put that on hold.

Being well aware that you cannot foresee the future, would you be able to give any indication when the updated VPL Jail will be a) in testing and b) released?

Feliz Navidad!
Jeroen

**Comment by jeroenhabets** [comment]
And Happy New Year 🎉 !

Being well aware that you cannot foresee the future, and well aware I am in no position to make any demands, would you be able and willing to give _any_ indication when the updated VPL Jail _could_ be a) in testing and b) released? Or else perhaps _any_ indication when you think to start on this?

Questions in _full_ appreciation of your work on this 🥇 !

**Comment by jeroenhabets** [comment]
Hi @jcrodriguez-dis,
Again in full appreciation of your work on this, would you be able to shed a light on this?
> Being well aware that you cannot foresee the future, and well aware I am in no position to make any demands, would you be able and willing to give any indication when the updated VPL Jail could be a) in testing and b) released? Or else perhaps any indication when you think to start on this?

as I would like to inform our VPL using customers.

P.S. Of course, I would be happy to offer some QA/test capacity if that helps.

**Comment by jeroenhabets** [comment]
I thought it was awfully quiet but found the work is taking place on the [JSON branch](https://github.com/jcrodriguez-dis/vpl-xmlrpc-jail/commits/JSON), if I'm not mistaken @jcrodriguez-dis  :rocket:. Cheers!

**Comment by jcrodriguez-dis** [comment]
Dear @jeroenhabets,
yes, the development on JSONRPC support at the execution server-side is almost finished. Now it is the turn of the Moodle plugin side that must be easier.

The planning is that both sides will support for a while XMLRPC and JSONRPC, this will allow a smooth transition to JSONRPC.

I accept your help for a QA/Test when both versions are ready.

Best regards,
Juan Carlos.

**Comment by jeroenhabets** [comment]
Dear @jcrodriguez-dis, 

> yes, the development on JSONRPC support at the execution server-side is almost finished. 

That is great news!

> I accept your help for a QA/Test when both versions are ready. 

Please note, that in order for my team to test we'd have to first implement our own VPL client in C#/.Net (see [my previous comment](https://github.com/jcrodriguez-dis/vpl-xmlrpc-jail/issues/49#issuecomment-1000137552))

Do you have an integration test/test client, or is there a specification of the new protocol for the client?

Kind regards,
Jeroen

**Comment by jeroenhabets** [comment]
Hi @jcrodriguez-dis ,
While revisiting open tickets in my own backlog I stumbled upon one about this feature.

By the looks of it you have managed to test w/o our help and released it:
https://vpl.dis.ulpgc.es/index.php/home/news/90-release-of-vpljail3-0-0

Congratulations 🥇 and appreciated 👍 !

Though not able to test right away, shall I close this ticket now?
Cheers, Jeroen
