### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by AnushaTeleparadigm** [jcrodriguez-dis/vpl-xmlrpc-jail#5]
Im Unable to start jail server getting 
Oct 10 10:59:44 tele-H81M-S1 vpl-jail-system[31399]: /sbin/start-stop-daemon: unable to start /etc/vpl/vpl-jail-server (Permission denied)
Please help me

**Comment by jcrodriguez-dis** [comment]
Hello Anusha,
please, give me a detailed report of the conditions where this problem happen. I need it to reproduce the problem and try to spot it.

Best regards.
Juan Carlos
