### ISSUE TITLE
Upgrade Apache Log4j

### ISSUE THREAD

**Issue by chyrka** [jcrodriguez-dis/vpl-xmlrpc-jail#51]
Is it possible to upgrade Apache  Log4j to the latest version because current installed version is Unsupported?

Path              : /jail/usr/share/maven-repo/org/apache/ant/ant-apache-log4j/1.10.7/ant-apache-log4j-1.10.7.jar
  Installed version : 1.10.7

  Path              : /jail/usr/share/java/ant-apache-log4j-1.10.7.jar
  Installed version : 1.10.7

  Path              : /usr/share/java/ant-apache-log4j-1.10.7.jar
  Installed version : 1.10.7

  Path              : /usr/share/maven-repo/org/apache/ant/ant-apache-log4j/1.10.7/ant-apache-log4j-1.10.7.jar
  Installed version : 1.10.7

**Comment by jcrodriguez-dis** [comment]
Dear chyrka,
The vpl-xmlrpc-jail software does not use or depend on log4j, feel free to update or remove log4j from your server. Remember to restart the vpl-xmlrpc-jail service to update the changes in the jail.

**Comment by jeroenhabets** [comment]
@chyrka can you close this issue, pls? TIA
