### ISSUE TITLE
Tips for intsllation of vpl jail server

### ISSUE THREAD

**Issue by informaticaopensource** [jcrodriguez-dis/vpl-xmlrpc-jail#53]
Hi all, i have a problem when i install
vpl jail server on my droplet ubuntu.
I receive message 
Problem binding to port 80: Could not bind to IPv4 or IPv6sue is:open  
I have apache on this port, where do i change the bind port ? 
Thank for attnesion.

**Comment by jcrodriguez-dis** [comment]
Dear informaticaopensource,
you can find the answer at

https://vpl.dis.ulpgc.es/documentation/vpl-jail-system-2.7.2/configuration.html#port

Best regards,
Juan Carlos.
